name: Deploy to EC2

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script_stop: true
          command_timeout: 30m
          script: |
            set -euxo pipefail
            cd /opt/dream-ferret/app
            git fetch --all
            git reset --hard origin/master
            docker compose -f docker-compose.prod.yml pull || true
            docker compose -f docker-compose.prod.yml up -d --build
            docker compose -f docker-compose.prod.yml ps
